### ISSUE TITLE
Can you add a license on this library ?

### ISSUE THREAD

**Issue by damdam-s** [akretion/roulier#1]
I saw that you didn't add a license to this project.
If you want to add one, what would it be ?

Thanks,
cc @lepistone, @hparfr

**Comment by lepistone** [comment]
My personal suggestion would be LGPL since that is the license of Odoo 9 community, and allows use in all versions of Odoo (and most other stuff).

Otherwise, if you want to specifically disallow use from proprietary code, including from Odoo 9 proprietary modules, than it could be the more restrictive AGPL.

Thanks!

**Comment by lepistone** [comment]
Also other permissive licenses like MIT or BSD or Apache should allow use almost everywhere (but IANAL).

**Comment by sebastienbeau** [comment]
Hi I will be more in favour of AGPLv3. Indeed even GNU discourage to use LGPL an use AGPL instead https://www.gnu.org/licenses/why-not-lgpl.html to force people using opensource brick to do opensource brick.

**Comment by lepistone** [comment]
Disclaimer: what follows is my personal feeling, you of course do what you feel for your own thing! 😸 

I personally don't share GNU's view of a free-software-only world. Many pieces of infrastructure like python, ruby, rails and so on have permissive licenses what allow them to be used in both free and commercial software, and I see that as a good thing for those projects (they get many contributions from people that use them in commercial software). In some cases like Rails even the core developers are using it for a proprietary thing (basecamp) and that's OK.

**Comment by hparfr** [comment]
For the moment it will be AGPL and other license upon request.
If we have many requests with the license, we will see.

**Comment by damdam-s** [comment]
@hparfr thanks
