### ISSUE TITLE
Geodis Response error

### ISSUE THREAD

**Issue by mourad-ehm** [akretion/roulier#16]
Geodis Response don't contain "attachement" key.

File "/workspace/parts/8-roulier/delivery_carrier_label_roulier/stock.py", line 219, in _call_roulier_api
    ret = roulier_instance.get_label(payload)
  File "/workspace/eggs/roulier-0.0.1-py2.7.egg/roulier/carriers/geodis/geodis.py", line 32, in get_label
    return self.get(data, 'demandeImpressionEtiquette')
  File "/workspace/eggs/roulier-0.0.1-py2.7.egg/roulier/carriers/geodis/geodis.py", line 26, in get
    parts = response['attachement']
KeyError: 'attachement'

**Comment by hparfr** [comment]
Not able to reproduce. Can you send me the request ?

**Comment by mourad-ehm** [comment]
Here is the request : 
-> ret = roulier_instance.get_label(payload)
(Pdb) payload
{'auth': {'login': u'******************', 'password': u'****************'}, 'to_address': {'city': u'Los Angeles', 'name': u'OpenElec Applications', 'zip': u'90001', 'firstname': '.', 'street1': u'23 Rockwell Lane', 'street2': '', 'phone': u'+1 312 349 2121', 'country': u'US', 'email': u'openelecapplications@yourcompany.example.com'}, 'from_address': {'city': u'Scranton', 'name': u'YourCompany', 'zip': u'18540', 'firstname': '.', 'street1': u'1725 Slough Ave.', 'street2': '', 'phone': u'+1 555 123 8069', 'country': u'FR', 'email': u'info@yourcompany.example.com'}, 'service': {'product': u'rrr', 'labelFormat': 'ZPL', 'agencyId': False, 'returnTypeChoice': 3, 'transportationAmount': 10, 'reference1': u'outgoing shipment your_company warehouse', 'customerId': ' ', 'shippingDate': '2016-10-12', 'shippingId': ' '}, 'parcel': {'weight': '0.0'}}

**Comment by hparfr** [comment]
The error response was not correctly handled.
