### ISSUE TITLE
Release 1.2.0

### ISSUE THREAD

**Issue by DylannCordel** [akretion/roulier#168]
Could you release roulier once #163 will be merged please ?

**Comment by florian-dacosta** [comment]
@DylannCordel Better late than never... I did fix the pypi release process and I release a new version today.
Sorry for the (big) delay...

**Comment by DylannCordel** [comment]
No worries, later is better than never and we all have many works to do for clients and (unfortunately) it's done before the opensource ;)
Thanks @florian-dacosta
