### ISSUE TITLE
Publish to PyPi

### ISSUE THREAD

**Issue by damdam-s** [akretion/roulier#7]
Hi @hparfr,

Do you plan to publish this library to Pypi ?

Thanks.

**Comment by hparfr** [comment]
Hi,

Yes. 
I plan to add Geodis and DPD then publish. I hope it will be ready before end of october.
If you need the publication before, we can do it sooner.

**Comment by damdam-s** [comment]
Thank for fast answering ;)

Maybe you can release the first version only with colissimo and add the others after with new version numbers ?

To be honest, I need it for my PR to be green on runbot builds (and not installing a python package by a github branch ...) :)

**Comment by hparfr** [comment]
https://pypi.python.org/pypi/roulier/
