### ISSUE TITLE
How to integrate this inside Odoo

### ISSUE THREAD

**Issue by Razgort** [akretion/roulier#81]
Hi do you have tips on how to integrate this module inside Odoo.

I assume it's with your other module named delivery-carrier on branches 9-roulier, origin/9-roulier.
But how does it work when you installed delivery-carrier inside Odoo in v9 ?

Thx in advance,

Razgort

**Comment by florian-dacosta** [comment]
Hi @Razgort 
I am discovering this issue. It is really old, I guess it is not relevant anymore, I'll close it.
(For integration with Odoo, if a module existe, for the carrier already, it should be here github.com/oca/delivery-carrier/ (on in a PR on this repo) and you just have to install the module and configure a carrier account to make it work.)
